project:
  type: website

website:
  title: "mpsa2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: presentation.qmd
        text: Presentation

format:
  html:
    theme: united
    css: styles.css
    toc: true



